package test;

import my.servlet.MyServlet;
import my.servlet.Request;
import my.servlet.Response;

/**
 * Created by bod on 10.08.15.
 */
public class ServletPrinter extends MyServlet {

    @Override
    public void doGET(Request req, Response response){
        response.setContentType("text/html; utf-8");
        response.getPrintStream().print(
                "<html> <head><title>Hello</title><meta charset=\"utf-8\"/></head>" +
                        "<body><h1>Hello, dear user!</h1>"+req.getParameter("print")+"<p><p><h5>Generated by Kirpychik</h5></body></html>"
        );

    }

    public void doPOST(Request request, Response response){
        response.setContentType("application/xml");
        response.getPrintStream().print("<xml><method>(POST)"+request.getMethod()+
                "</method><print>"+request.getParameter("print")+"</print></xml>");
    }
}
